sudo: required
dist: trusty
language: cpp
compiler: gcc
addons:
  postgresql: 9.1
  apt:
    packages:
      - libboost-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libfcgi-dev
      - libmemcached-dev
      - libxml2-dev
      - libcrypto++-dev
script:
  - sudo apt-get install -yqq libpqxx-dev libboost-locale-dev
  - ./autogen.sh
  - ./configure
  - make
  - make check
after_failure:
  - cat test-suite.log
